blog/urls.py
from django.urls import path
from .views import (
    ArticleList,
    ArticleDetail,
    ArticlePreview,
    CategoryList,
    AuthorList,
    SearchList
)


app_name = "blog"
urlpatterns = [
    path("", ArticleList.as_view(), name="home"),
    path("page/<int:page>", ArticleList.as_view(), name="home"),
    path("article/<slug:slug>", ArticleDetail.as_view(), name="detail"),
    path("preview/<int:pk>", ArticlePreview.as_view(), name="preview"),
    path("category/<slug:slug>", CategoryList.as_view(), name="category"),
    path("category/<slug:slug>/page/<int:page>", CategoryList.as_view(), name="category"),
    path("author/<slug:username>", AuthorList.as_view(), name="author"),
    path("author/<slug:username>/page/<int:page>", AuthorList.as_view(), name="author"),
    path("search/", SearchList.as_view(), name="search"),
    path("search/page/<int:page>", SearchList.as_view(), name="search"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from account.views import Login, Register, activate
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", include("blog.urls")),
    path("", include("django.contrib.auth.urls")),
    path("login/", Login.as_view(), name="login"),
    path("register/", Register.as_view(), name="register"),
    path('activate/<uidb64>/<token>/', activate, name='activate'),
    path("account/", include("account.urls")),
    path('comment/', include('comment.urls')),
    path("admin/", admin.site.urls),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.urls import reverse
from account.models import User
from django.utils import timezone
from django.utils.html import format_html
from extensions.utils import jalali_converter
from django.contrib.contenttypes.fields import GenericRelation
from comment.models import Comment


# My manager
class ArticleManager(models.Manager):
  def published(self):
    return self.filter(status="p")


class CategoryManager(models.Manager):
  def active(self):
    return self.filter(status=True)


# Create your models here.
class IPAddress(models.Model):
  ip_address = models.GenericIPAddressField(verbose_name="آدرس آی پی")


class Category(models.Model):
  parent = models.ForeignKey("self", default=None, null=True, blank=True, on_delete=models.SET_NULL, related_name="children",  verbose_name="زیر دسته")
  title = models.CharField(max_length=200, verbose_name = "عنوان دسته بندی")
  slug = models.SlugField(max_length=100, unique=True, verbose_name = "آدرس مقاله")
  status = models.BooleanField(default=True, verbose_name="آیا نمایش داده شود؟")
  position = models.IntegerField(verbose_name = "پوزیشن")
  
  
  class Meta:
    verbose_name = "دسته بندی"
    verbose_name_plural = "دسته بندی ها"
    ordering = ["parent__id", "position"]
    
  def __str__(self):
      return self.title
    
  objects = CategoryManager()
    

class Article(models.Model):
  STATUS_CHOICES = (
    ("d", "پیش نویس"),      # draft
    ("p", "منتشر شده"),     # publish
    ("i", "در حال بررسی"),  # investigation
    ("b", "برگشت داده شده") # back
  )
  author = models.ForeignKey(User, null=True, on_delete=models.SET_NULL, related_name="articles", verbose_name="نویسنده")
  title = models.CharField(max_length=200, verbose_name = "عنوان مقاله")
  slug = models.SlugField(max_length=100, unique=True, verbose_name = "آدرس مقاله")
  category = models.ManyToManyField(Category, verbose_name="دسته بندی", related_name="articles")
  description = models.TextField(verbose_name = "محتوا")
  thumbnail = models.ImageField(upload_to="images", verbose_name = "تصویر مقاله")
  publish = models.DateTimeField(default=timezone.now, verbose_name = "زمان انتشار")
  created = models.DateTimeField(auto_now_add=True)
  update = models.DateTimeField(auto_now=True)
  is_special = models.BooleanField(default=False, verbose_name="مقاله ویژه")
  status = models.CharField(max_length=1, choices=STATUS_CHOICES, verbose_name = "وضعیت")
  comments = GenericRelation(Comment)
  hits = models.ManyToManyField(IPAddress, through="ArticleHit", blank=True, related_name="hits", verbose_name="بازدید ها")
  
  class Meta:
    verbose_name = "مقاله"
    verbose_name_plural = "مقالات"
    ordering = ["-publish"]
  
  def __str__(self):
    return self.title
  
  def get_absolute_url(self):
    return reverse("account:home")
  
  def jpublish(self):
    return jalali_converter(self.publish)
  
  jpublish.short_description = "زمان انتشار"
  
  def thumbnail_tag(self):
    return format_html("<img width='100px' height='75px' style='border-radius: 5px;' src='{}'>".format(self.thumbnail.url))
  
  thumbnail_tag.short_description = "عکس"
  
  def category_to_str(self):
    return ", ".join([category.title for category in self.category.active()])
  
  category_to_str.short_description = "دسته بندی"
  
  objects = ArticleManager()
  
class ArticleHit(models.Model):
  article = models.ForeignKey(Article, on_delete=models.CASCADE)
  ip_address = models.ForeignKey(IPAddress, on_delete=models.CASCADE)
  created = models.DateTimeField(auto_now_add=True)

blog/views.py
from django.core.paginator import Paginator
from account.models import User
from django.shortcuts import render, get_object_or_404
from django.views.generic import ListView, DetailView
from account.mixins import AuthorAccessMixin
# from django.http import Http404
from .models import Article, Category
from django.db.models import Q

# Create your views here.
class ArticleList(ListView):
  queryset = Article.objects.published()
  paginate_by = 3


class ArticleDetail(DetailView):
  def get_object(self):
    slug = self.kwargs.get("slug")
    article = get_object_or_404(Article.objects.published(), slug=slug)
    
    ip_address = self.request.user.ip_address
    viewsCount = article.hits.all()
    if ip_address not in viewsCount:
      article.hits.add(ip_address)
    
    return article
  
  
class ArticlePreview(AuthorAccessMixin, DetailView):
  def get_object(self):
    pk = self.kwargs.get("pk")
    return get_object_or_404(Article, pk=pk)
  

class CategoryList(ListView):
  paginate_by = 3
  template_name = "blog/category_list.html"
  
  def get_queryset(self):
    global category
    slug = self.kwargs.get("slug")
    category = get_object_or_404(Category.objects.active(), slug=slug)
    return category.articles.published()
  
  def get_context_data(self, **kwargs):
    slug = self.kwargs.get("slug")
    context = super().get_context_data(**kwargs)
    context["category"] = category
    return context
  
  
class AuthorList(ListView):
  paginate_by = 3
  template_name = "blog/author_list.html"
  
  def get_queryset(self):
    global author
    username = self.kwargs.get("username")
    author = get_object_or_404(User, username=username)
    return author.articles.published()
  
  def get_context_data(self, **kwargs):
    slug = self.kwargs.get("slug")
    context = super().get_context_data(**kwargs)
    context["author"] = author
    return context


class SearchList(ListView):
  paginate_by = 3
  template_name = "blog/search_list.html"
  
  def get_queryset(self):
    search = self.request.GET.get("q")
    return Article.objects.filter(Q(description__icontains=search) | Q(title__icontains=search))
  
  def get_context_data(self, **kwargs):
    context = super().get_context_data(**kwargs)
    context["search"] = self.request.GET.get("q")
    return context

comment/views/base.py
from django.views.generic import FormView

from comment.conf import settings
from comment.context import DABContext
from comment.responses import DABResponseData
from comment.messages import EmailInfo
from comment.service.email import DABEmailService
from comment.forms import CommentForm


class BaseCommentView(FormView, DABResponseData):
    form_class = CommentForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['comment_form'] = context.pop('form')
        context.update(DABContext(self.request))
        return context

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['request'] = self.request
        return kwargs


class CommentCreateMixin(BaseCommentView):
    email_service = None

    def _initialize_email_service(self, comment, request):
        self.email_service = DABEmailService(comment, request)

    def _send_notification_to_followers(self, comment, request):
        if settings.COMMENT_ALLOW_SUBSCRIPTION:
            self._initialize_email_service(comment, request)
            self.email_service.send_notification_to_followers()

    def perform_save(self, comment, request):
        comment.save()
        self._send_notification_to_followers(comment, request)
        comment.refresh_from_db()
        return comment

    def _handle_anonymous(self, comment, request, api=False):
        self._initialize_email_service(comment, request)
        self.email_service.send_confirmation_request(api=api)
        self.anonymous = True
        self.msg = EmailInfo.CONFIRMATION_SENT

    def perform_create(self, comment, request, api=False):
        if settings.COMMENT_ALLOW_ANONYMOUS and not comment.user:
            self._handle_anonymous(comment, request, api)
        else:
            comment = self.perform_save(comment, request)
        return comment

templates/blog/about.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Clean Blog - Start Bootstrap Theme</title>
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet" type="text/css" />
        <link href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="css/styles.css" rel="stylesheet" />
    </head>
    <body>
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light" id="mainNav">
            <div class="container px-4 px-lg-5">
                <a class="navbar-brand" href="index.html">Start Bootstrap</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    Menu
                    <i class="fas fa-bars"></i>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ms-auto py-4 py-lg-0">
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="index.html">Home</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="about.html">About</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="post.html">Sample Post</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="contact.html">Contact</a></li>
                    </ul>
                </div>
            </div>
        </nav>
        <!-- Page Header-->
        <header class="masthead" style="background-image: url('assets/img/about-bg.jpg')">
            <div class="container position-relative px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <div class="page-heading">
                            <h1>About Me</h1>
                            <span class="subheading">This is what I do.</span>
                        </div>
                    </div>
                </div>
            </div>
        </header>
        <!-- Main Content-->
        <main class="mb-4">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Saepe nostrum ullam eveniet pariatur voluptates odit, fuga atque ea nobis sit soluta odio, adipisci quas excepturi maxime quae totam ducimus consectetur?</p>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eius praesentium recusandae illo eaque architecto error, repellendus iusto reprehenderit, doloribus, minus sunt. Numquam at quae voluptatum in officia voluptas voluptatibus, minus!</p>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aut consequuntur magnam, excepturi aliquid ex itaque esse est vero natus quae optio aperiam soluta voluptatibus corporis atque iste neque sit tempora!</p>
                    </div>
                </div>
            </div>
        </main>
        <!-- Footer-->
        <footer class="border-top">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <ul class="list-inline text-center">
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                        </ul>
                        <div class="small text-center text-muted fst-italic">Copyright &copy; Your Website 2023</div>
                    </div>
                </div>
            </div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="js/scripts.js"></script>
    </body>
</html>

templates/blog/article_detail.html
{% extends "blog/base.html" %}

{% load base_tags %}
{% block title %} | {{ object.title }} {% endblock %}

{% block main %}

    <!-- Page Header-->
    <header class="masthead" style="background-image: url('{{ object.thumbnail.url }}'); width: 100%">
        <div class="container position-relative px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5 justify-content-center">
                <div class="col-md-10 col-lg-8 col-xl-7">
                    <div class="site-heading">
                        <h1 class="site-heading-title">{{ object.title }}</h1>
                        {% if article.is_special %}
                            <span 
                                class="badge badge-dark"
                                style="font-size: 12px; background-color: red; border-radius: 10%;"
                            >
                                ویژه
                            </span>
                        {% endif %}
                        <time>{{ object.jpublish }}</time>
                        <div>{{ object.hits.count }}</div>
                    </div>
                </div>
            </div>
        </div>
    </header>
       
    <!-- Post Content-->
    <article class="mb-4">
        <aside>
            {% popular_articles %}
            {% hot_articles %}
        </aside>
        <div class="container px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5 justify-content-center">
                <div class="col-md-10 col-lg-8 col-xl-7 text-justify">
                    {% if object.is_special %}
                        {% if user.is_authenticated and user.is_special_user or user == object.author or user.is_superuser %}
                            {{ object.description|safe }}
                        {% else %}
                            {{ article.description|striptags|truncatewords:30 }}
                            <p class="alert alert-warning">این مقاله ویژه است و برای مشاهده آن باید <a class="alert-link" href="#">اشتراک ویژه</a> تهیه بکنید.</p>
                        {% endif %}
                    {% else %}
                        {{ object.description|safe }}
                    {% endif %}
                    {% load comment_tags %}
                    {% render_comments object request %}
                    {% include_bootstrap %}
                </div>
            </div>
        </div>
    </article>
{% endblock %}

templates/blog/article_list.html
{% extends "blog/list.html" %}

{% block header %}{% endblock %}

{% block previous_page_url %}
    {% url 'blog:home' page_obj.previous_page_number %}
{% endblock %}
{% block next_page_url %}
    {% url 'blog:home' page_obj.next_page_number %}
{% endblock %}

templates/blog/author_list.html
{% extends "blog/list.html" %}

{% block header %}
  <h3 class="alert alert-primary text-center">نویسنده: {{ author.get_full_name }}</h3>
{% endblock %}


{% block previous_page_url %}
  {% url 'blog:author' author.username page_obj.previous_page_number %}
{% endblock %}
{% block next_page_url %}
  {% url 'blog:author' author.username page_obj.next_page_number %}
{% endblock %}

templates/blog/base.html
{% load static %}
{% load base_tags %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>بلاگ {% block title %}{% endblock %}</title>
        <link rel="icon" type="image/x-icon" href="{% static 'blog/assets/favicon.ico' %}" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet" type="text/css" />
        <link href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'blog/css/styles.css' %}" rel="stylesheet" />
        <link href="{% static 'blog/css/rtl.css' %}" rel="stylesheet" />
    </head>
    <body>
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light" id="mainNav">
            <div class="container px-4 px-lg-5">
                <a class="navbar-brand" href="{% url "blog:home" %}">{% title %}</a>
                <button 
                    class="navbar-toggler"
                    type="button"
                    data-bs-toggle="collapse"
                    data-bs-target="#navbarResponsive"
                    aria-controls="navbarResponsive"
                    aria-expanded="false"
                    aria-label="Toggle navigation"
                >
                    Menu
                    <i class="fas fa-bars"></i>
                </button>
                {% category_navbar %}
            </div>
        </nav>
        
        {% block main %}

        {% endblock %}

        <!-- Footer-->
        <footer class="border-top">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <ul class="list-inline text-center">
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                        </ul>
                        <div class="small text-center text-muted fst-italic">Copyright &copy; Your Website 2023</div>
                    </div>
                </div>
            </div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="js/scripts.js"></script>
    </body>
</html>

templates/blog/category_list.html
{% extends "blog/list.html" %}

{% block header %}
  <h3 class="alert alert-primary text-center">دسته بندی: {{ category.title }}</h3>
{% endblock %}


{% block previous_page_url %}
  {% url 'blog:category' category.slug page_obj.previous_page_number %}
{% endblock %}
{% block next_page_url %}
  {% url 'blog:category' category.slug page_obj.next_page_number %}
{% endblock %}

templates/blog/list.html
{% extends "blog/base.html" %}

{% block title %}{% endblock %}
{% load humanize %}

{% load static %}
{% load base_tags %}

{% block main %}

    <!-- Page Header-->
    <header class="masthead" style="background-image: url('{% static "blog/assets/img/home-bg.jpg" %}')">
        <div class="container position-relative px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5 justify-content-center">
                <div class="col-md-10 col-lg-8 col-xl-7">
                    <div class="site-heading">
                        <h1>بلاگ روزانه</h1>
                    </div>
                </div>
            </div>
        </div>
    </header>

    <!-- Main Content-->
    <div class="container px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">

                {% block header %}{% endblock %}
                
                <aside>
                    {% popular_articles %}
                    {% hot_articles %}
                </aside>

                {% for article in object_list %}

                    <!-- Post preview-->
                    <div class="post-preview">
                        <a href="{% url 'blog:detail' article.slug %}">
                            <h2 class="post-title">
                                {{ article.title }}
                                {% if article.is_special %}
                                    <span 
                                        class="badge badge-dark"
                                        style="font-size: 12px; background-color: red; border-radius: 10%;"
                                    >
                                        ویژه
                                    </span>
                                {% endif %}
                            </h2>
                            <h3 class="post-subtitle">{{ article.description|striptags|truncatewords:30 }}</h3>
                        </a>
                        <p class="post-meta">
                            نوشته شده توسط
                            <a href="{% url "blog:author" article.author %}">{{ article.author.get_full_name }}</a>
                            {{ article.publish|naturaltime }}
                            <div>
                                {% for cat in article.category.active %}
                                <a href="{% url "blog:category" cat.slug %}">#{{ cat.title }}</a>
                                {% endfor %}
                            </div>
                            <div>بازدید ها: {{ article.hits.count }} </div>
                        </p>
                    </div>
                    <!-- Divider-->
                    <hr class="my-4" />

                {% empty %}
                    <p>متاسفانه محتوایی برای نمایش وجود ندارد.</p>
                {% endfor %}

                <!-- Pager-->
                {% if is_paginated %}
                    <div class="d-flex justify-content-end mb-4">
                        {% if page_obj.has_previous %}
                            <a class="btn btn-primary text-uppercase" href="{% block previous_page_url %}{% endblock %}">پست های جدید &rarr;</a>
                        {% endif %}
                        {% if page_obj.has_next %}
                            <a class="btn btn-primary text-uppercase" href="{% block next_page_url %}{% endblock %}">پست های قدیمی &larr;</a>
                        {% endif %}
                    </div>
                {% endif %}
            </div>
        </div>
    </div>

{% endblock %}

templates/blog/search_list.html
{% extends "blog/list.html" %}

{% block header %}
  <h3 class="alert alert-primary text-center">جستوجو: {{ search }}</h3>
{% endblock %}


{% block previous_page_url %}
  {% url 'blog:search' page_obj.previous_page_number %}?q={{ search }}
{% endblock %}
{% block next_page_url %}
  {% url 'blog:search' page_obj.next_page_number %}?q={{ search }}
{% endblock %}